projectk/Controllers/FunVideoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projectk.Models;
using Spring.Social.OAuth1;
using Spring.Social.Dropbox.Api;
using Spring.Social.Dropbox.Connect;
using Projectk;
namespace projectk.Controllers
{
    public class FunVideoController : Controller
    {
        private ProjectkContext db = new ProjectkContext();
       
        //
        // GET: /Hotgirl/

        public ActionResult Index()
        {
            int EndID = 0;
            List<Article> articles = Variable.GetVideo(ref EndID);
            ViewBag.EndID = EndID;
            db.SaveChanges();
            return View(articles);
           
        }

        public string load(int id = 0)
        {
            string currentURL = Request.Url.PathAndQuery;
            int EndID = 0;
            List<Article> articles = Variable.GetVideo(ref EndID, id);
            return Variable.GenerateVideos(articles, EndID, currentURL);

        } 


        //
        // GET: /Hotgirl/Details/5

        public ActionResult Details(int id = 0)
        {
            //set pageview
            if (Pageview.A[id] == null)
            {
                Pageview.A[id] = 1;

            }
            else
            {
                Pageview.A[id] = int.Parse(Pageview.A[id].ToString()) + 1;
            }
            //end set pageview
            Article article = db.Articles.Find(id);
            article.UserProfile = db.UserProfiles.Where(a => a.UserName == article.UserName).FirstOrDefault();
            ViewBag.Next = -1;
            ViewBag.Prev = -1;
            Article Next = db.Articles.Where(a => a.ID > id && a.Cat == article.Cat).FirstOrDefault();
            if (Next != null)
                ViewBag.Next = Next.ID;
            Article Prev = db.Articles.Where(a => a.ID < id && a.Cat == article.Cat).FirstOrDefault();
            if (Prev != null)
                ViewBag.Pre = Prev.ID;
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

projectk/Controllers/SuggestionController.cs
using projectk.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projectk.Controllers
{
    public class SuggestionController : Controller
    {
        private ProjectkContext db = new ProjectkContext();
        //
        // GET: /Suggestion/
        [ChildActionOnly]
        public ActionResult Index()
        {
            List<Article> listTopVideo = db.Articles.Where(a => a.Cat == (int)Cats.Video).OrderByDescending(a => a.DatePost).Take(5).ToList();
            List<Article> listTopFunny = db.Articles.Where(a => a.Cat == (int)Cats.Funny).OrderByDescending(a => a.DatePost).Take(5).ToList();
            ViewBag.listTopView = listTopVideo;
            ViewBag.listTopFunny = listTopFunny;
             
            return PartialView();
        }


        [ChildActionOnly]
        public ActionResult MostViewed()
        {
            List<Article> articles = db.Articles.OrderByDescending(a => a.PageView).Take(5).ToList();
            ViewBag.articles = articles; 
            return PartialView();
        }


        [ChildActionOnly]
        public ActionResult OlderFunny(int ID)
        {
            List<Article> articles = db.Articles.Where(a => a.Cat == (int)Cats.Funny && a.ID < ID).OrderByDescending(a => a.DatePost).Take(8).ToList();
            ViewBag.articles = articles;
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult OlderVideo(int ID)
        {
            List<Article> articles = db.Articles.Where(a => a.Cat == (int)Cats.Video && a.ID < ID).Take(8).ToList();
            ViewBag.articles = articles;
            return PartialView();
        }


    }
}

projectk/Views/FunVideo/Details.cshtml
@model projectk.Models.Article

@{
    ViewBag.Title = "Video - " + @Model.Name;
    ViewBag.url = @Request.Url;
    ViewBag.title = @Model.Name;
    ViewBag.image = "http://img.youtube.com/vi/" + Model.getYoutubeID() + "/1.jpg";
}

 
<div class="aitem">
    <div class="row-fluid">
        <div class="alert alert-info"> 
            <button type="button" class="close" data-dismiss="alert">×</button>
            Sử dụng cáo phím <- hay -> trên bàn phím của bạn để xem các bài khác
        </div>
        <div class="title-detail" style="">
            <div class="span2">

                <div class="pull-left a-prev a-control">
                @if(@ViewBag.Prev!=-1){
                    <a title="Bài trước" class="Next-Button" href="/funvideo/@ViewBag.Prev">
                    </a>
                }
                </div>
            </div>
            <div class="span8" style="line-height: 70px;">
                <h3 style="color: #ffffff;">@Model.Name </h3>
            </div>
            <div class="span2">
                <div class="pull-right a-next a-control">
                 @if(@ViewBag.Next!=-1){
                    <a  class="Next-Button" title="Bài kế tiếp" href="/funvideo/@ViewBag.Next">
                    </a>
                 }
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">

        <div class="author-info" style="">
            <div class="span6">
                <div style="text-align: center;" class="a-rate">
                    <div style="margin-right: 15px;">
                        <span class="badge badge-success">View: @Model.PageView</span>
                        <span class="badge badge-warning">Comments:
                                <fb:comments-count href="@Request.Url.AbsoluteUri" />
                            </fb:comments-count></span>
                    </div>
                    <div class="fb-like" data-href="@Request.Url.AbsoluteUri" data-send="true" data-layout="button_count"
                        data-width="450" data-show-faces="true">
                    </div>
                </div>
                <div style="clear: both;"></div>
                <div>
                    <span>Nguồn: @Model.Source</span>
                </div>
            </div>
            <div class="span6">
                <div style="float: right; color: #000;">
                    <span>Được chia sẻ bởi </span><span><a href="#">
                    @Model.UserName
                        
                    </a></span>
                    <span class="badge badge-success">Like: @Model.UserProfile.TotalLike </span>

                </div>

            </div>

        </div>
    </div>
     
    <div class="row-fluid">

        <div class="span12">
            <div class="video-container">
                <iframe width="560" height="315" src="http://www.youtube.com/embed/@Model.getYoutubeID()" frameborder="0" allowfullscreen></iframe>

            </div>
        </div>
    </div>

</div>
<div class="suggest-older">

    @{
        Html.RenderAction("OlderVideo", "Suggestion", new { ID = @Model.ID });
    }
</div>
<div id="commentbox-wrapper">
 <div class="fb-comments" data-href="@Request.Url.AbsoluteUri" data-width="470" data-num-posts="10"></div> 
 </div>

  








  

projectk/Views/FunVideo/Index.cshtml
@model IEnumerable<projectk.Models.Article>

@{
    ViewBag.Title = "Index";
}

 
@Html.Raw(Projectk.Variable.GenerateVideos((List<projectk.Models.Article>)Model, ViewBag.EndID, Context.Request.Url.ToString()))

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#load').live({
                click: function () {
                    $('.loading').show();
                    var urlAJ = "/funvideo/load/" + $('#EndID').val();
                    $.ajax({
                        url: urlAJ, success: function (result) {
                            $('.loading').remove();
                            $('.buttonload').remove();
                            $(".article-content").append(result);
                            $(document).ready(function () {
                                $("img.lazy").lazyload({
                                    effect: "fadeIn", failure_limit: 10
                                }).removeClass("lazy");
                            });
                        }
                    });
                }
            });


        })
    </script>
    @if (!Projectk.Variable.IsMobileClient())
    {
        <script type="text/javascript">
            var topHeight = 65;
            $(window).scroll(function () {
                $('.item-image').each(function () {
                    var ctop = $(this).position().top;
                    var cheight = $(this).height();

                    var info = $(this).parent('div').parent('.article_item').find('.aitem-top');
                    var iheight = info.height();
                    var d = ctop - $(window).scrollTop() - topHeight;
                    var margintop = info.css('margin-top');
                    if (d > 0) {
                        info.removeClass('FixTitle');
                        info.css('width', (info.parent('.span4').width() - 20) + 'px');
                        return false;
                    }
                    if (d <= 0 && ((-d) < (cheight - iheight))) {
                        info.addClass('FixTitle');
                        info.css('width', (info.parent('.span4').width() - 20) + 'px');
                    }
                    else {
                        info.removeClass('FixTitle');
                    }
                });
            });
        </script>
    }
}