projectk/Controllers/ImageUploadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projectk.Models;
using DropNet;
using Projectk;
using Spring.Social.OAuth1;
using Spring.Social.Dropbox.Api;
using Spring.Social.Dropbox.Connect;
using System.Web.Security;
using System.Drawing;
using System.IO;

namespace projectk.Controllers
{
    public class ImageUploadController : Controller
    {
        private ProjectkContext db = new ProjectkContext();

        //
        // GET: /Article/

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Hotgirl");
            var articles = db.Articles.Where(a => a.UserName == User.Identity.Name).OrderByDescending(a => a.DatePost).Take(100).Include(a => a.UserProfile).ToList();
            return View(articles.ToList());
        }



        //
        // GET: /Article/Create

        public ActionResult Create(int id=0)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToAction("Index", "Hotgirl");
            //ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Article/Create

        [HttpPost]
        public ActionResult Create(Article article)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToAction("Index", "Hotgirl");
            if (ModelState.IsValid)
            {
                int cat = int.Parse(Request.Form["imageType"].ToString()); ;

                IOAuth1ServiceProvider<IDropbox> dropboxProvider =
         new DropboxServiceProvider(Variable.ApiKey, Variable.ApiSecret, AccessLevel.Full);

                IDropbox _client = dropboxProvider.GetApi(Variable.UserToken, Variable.UserSecret);


                var uniqueID = Variable.GetRandomInteger();



                //upload file
                if (Request.Files.Count == 0 && Request.Files[0].FileName!="")
                    return RedirectToAction("Index");

                HttpPostedFileBase ofile = Request.Files[0];
                string filename = uniqueID + "_" + ofile.FileName;
                if (ofile.ContentLength > 0)
                {
                    string localURL1="";
                    string ThumbnailURL = "";
                    string DropboxURL = "";
                    if (cat == (int)Cats.Funny)
                    {
                        DropboxURL = "/conmeno/funny/" + filename;
                        localURL1 = Variable.WebFolder() + "/Upload/funny/" + filename;
                        ThumbnailURL = Variable.WebFolder() + "/Upload/funny/thumbnail/" + filename;
                    }
                    else {
                        localURL1 = Variable.WebFolder() + "/Upload/hotgirl/" + filename;
                        ThumbnailURL = Variable.WebFolder() + "/Upload/hotgirl/thumbnail/" + filename;
                        DropboxURL = "/conmeno/hotgirl/" + filename;
                    }

                    ofile.SaveAs(localURL1);
                    var image = System.Drawing.Image.FromFile(localURL1);
                   
                    Spring.IO.FileResource file = new Spring.IO.FileResource(localURL1);

                   
                    if(cat==(int)Cats.Funny) 
                    DropboxURL="/conmeno/funny/" + filename;
                    else
                        DropboxURL = "/conmeno/hotgirl/" + filename;


                    //_client.UploadFileAsync(file, DropboxURL);
                    var upload = _client.UploadFileAsync(file, DropboxURL).Result;

                    //_client.UploadFile("/conmeno/", uniqueID + "_" + ofile.FileName, Variable.ReadFully(ofile.InputStream));
                    article.ExternalURL = DropboxURL;
                    article.LocalURL = localURL1.Replace(Variable.WebFolder(), "");


                    var temp = _client.GetMediaLinkAsync(article.ExternalURL);


                    if (temp != null) article.DropboxShareLink = temp.Result.Url;
                    article.DropboxShareLinkExpire = DateTime.Now.AddHours(3);
                    Size thumbnailSize = GetThumbnailSize(image);
                    var thumImg = image.GetThumbnailImage(thumbnailSize.Width, thumbnailSize.Height, () => false, IntPtr.Zero);
                    thumImg.Save(ThumbnailURL);
                    article.ThumbnailURL = ThumbnailURL.Replace(Variable.WebFolder(), "");
                    //var a1 = _client.DownloadThumbnailAsync(article.ExternalURL, ThumbnailFormat.Jpeg, ThumbnailSize.ExtraLarge).Result;
                    //if (a1.Content.Count()>0)
                    //{
                    //    MemoryStream ms = new MemoryStream(a1.Content);
                    //    Image returnImage = Image.FromStream(ms);
                    //    returnImage.Save(ThumbnailURL);
                    //    article.ThumbnailURL = ThumbnailURL.Replace(Variable.WebFolder(), "");
                    //}
                    //article.ThumbnailData = a1.Content;


                }

                //endupload file

                //article.UserID = currentUser.;


                article.UserID = 1;
                article.UserName = User.Identity.Name;
                if (cat == (int)Cats.Funny) 
                article.Cat = (int)Cats.Funny;
                else
                    article.Cat = (int)Cats.HotGirl;
                article.Status = 0;
                if (Variable.AutoApprove)
                    article.Status = 1;
                article.DatePost = DateTime.Now;
                db.Articles.Add(article);
                db.SaveChanges();  
                
                return RedirectToAction("Index");
            }

            // ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", article.CategoryID);
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", article.UserID);
            return View(article);
        }
        public Size GetThumbnailSize(Image original)
        {
            // Maximum size of any dimension.
            const int maxPixels = 200;

            // Width and height.
            int originalWidth = original.Width;
            int originalHeight = original.Height;

            // Compute best factor to scale entire image based on larger dimension.
            double factor;
            if (originalWidth > originalHeight)
            {
                factor = (double)maxPixels / originalWidth;
            }
            else
            {
                factor = (double)maxPixels / originalHeight;
            }

            // Return thumbnail size.
            return new Size((int)(originalWidth * factor), (int)(originalHeight * factor));
        }
        //
        // GET: /Article/Create

        public ActionResult Check(int type=1)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToAction("Index", "Hotgirl");
            Cats temp = (Cats)type;
            var articles = db.Articles.Where(a => a.Cat == (int)temp).OrderByDescending(a => a.DatePost).Take(100).Include(a => a.UserProfile).ToList();
            
            return View(articles.ToList());
        }


        //
        // GET: /Article/Delete/5

        public ActionResult Delete(long id = 0)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToAction("Index", "Hotgirl");
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        //
        // POST: /Article/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToAction("Index", "Hotgirl");
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("check");
        }


        public ActionResult Approve(long id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Hotgirl");
            Article article = db.Articles.Find(id);
            article.Status = 1; 
            db.SaveChanges();
            return RedirectToAction("Check");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

projectk/Controllers/VideoUploadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projectk.Models;
using DropNet;
using Projectk;
using Spring.Social.OAuth1;
using Spring.Social.Dropbox.Api;
using Spring.Social.Dropbox.Connect;
using System.Web.Security;

namespace projectk.Controllers
{
    public class VideoUploadController : Controller
    {
        private ProjectkContext db = new ProjectkContext();

        //
        // GET: /Article/

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "FunVideo");
            //var articles = db.Articles.Include(a => a.UserProfile);
            //return View(articles.ToList());
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

       
        //
        // POST: /Article/Create

        [HttpPost]
        public ActionResult Index(Article article)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "FunVideo");
            if (ModelState.IsValid)
            { 

                db.Articles.Add(article);
                article.DropboxShareLinkExpire = DateTime.Now;
                //endupload file
                //MembershipUser currentUser;
                //currentUser = Membership.GetUser();

                //article.UserID = currentUser.;


                article.UserID = 1;
                article.UserName = User.Identity.Name;
                article.Cat = (int)Cats.Video;
                article.DatePost = DateTime.Now;
                article.Status = 0;
                if (Variable.AutoApprove)
                    article.Status = 1;
                db.SaveChanges(); 

                return RedirectToAction("Index");
            }

           // ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", article.CategoryID);
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", article.UserID);
            return View(article);
        }

       

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

projectk/Views/ImageUpload/Check.cshtml
@model IEnumerable<projectk.Models.Article>

@{
    ViewBag.Title = "Check";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    table tr th
    {
        text-align: left;
        font: bold 11px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
        color: #6D929B;
        border: 1px solid #C1DAD7;
        letter-spacing: 2px;
        text-transform: uppercase;
        text-align: left;
        padding: 6px 6px 6px 12px;
    }

    table tr td
    {
        border: 1px solid #C1DAD7;
        background: #fff;
        padding: 6px 6px 6px 12px;
        color: #6D929B;
    }
</style>
<h2>Kiểm duyệt bài đăng</h2>

<div style="margin: 20px 0px;">
    @{
        var class1 = "btn-inverse";
        var class2 = "btn-inverse";
        var class3 = "btn-inverse";
        var class4 = "btn-inverse";
        bool isVideo = false;
    
    
    }
    @if (Request.QueryString["type"] == null) { class1 = "btn-success"; }
    @if (Request.QueryString["type"] != null && Request.QueryString["type"].ToString() == "1") { class1 = "btn-success"; }
    @Html.ActionLink("Funny", "Check", new { type = 1 }, new { @class = "btn " + class1 })
    @if (Request.QueryString["type"] != null && Request.QueryString["type"].ToString() == "2") { class2 = "btn-success";  }
    @Html.ActionLink("Hotgirl", "Check", new { type = 2 }, new { @class = "btn " + class2 })
    @if (Request.QueryString["type"] != null && Request.QueryString["type"].ToString() == "3") { class3 = "btn-success"; isVideo = true; }
    @Html.ActionLink("Video", "Check", new { type = 3 }, new { @class = "btn " + class3 })
    @if (Request.QueryString["type"] != null && Request.QueryString["type"].ToString() == "4") { class4 = "btn-success"; }
    @Html.ActionLink("Truyện", "Check", new { type = 4 }, new { @class = "btn " + class4 })
</div>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThumbnailData)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatePost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PageView)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Like)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (isVideo)
                {
                 <a href="/video/details/@item.ID"><img alt="video" src="http://img.youtube.com/vi/@item.getYoutubeID()/1.jpg" /></a> 
                }
                else
                {
                    //if (item.ThumbnailData != null)
                    //{
<a href="/funny/details/@item.ID">
                        <img alt="@item.Name" src="@item.ThumbnailURL"
                    />
                    </a> 
                
                    //}
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PageView)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Like)
            </td>
            <td>
                @item.GetStatus()
            </td>
            <td>
                @{
                if (item.Status == 0)
                { 
                    
                    @Html.ActionLink("Duyệt", "Approve", new { id = item.ID }, new { @class = "btn btn-success" })              
                  

                }
                }
                <br />
                <br />
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
            </td>

        </tr>
    }

</table>

projectk/Views/ImageUpload/Create.cshtml
@model projectk.Models.Article

@{
    int cat = 0;
    if (Request.QueryString["id"] != null)
    {
        cat = 1;
    }
    ViewBag.Title = "Upload funny";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .myinput
    {
        margin: 0!important;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
  
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Upload hình ảnh vui nhộn</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>


        <div class="editor-label">
            Thể loại
        </div>
        <div class="editor-field">
            <div style="line-height: 20px;">

                @if (cat == 0)
                {
                    <span>
                        <input class="myinput" checked="checked" type="radio" value="1" name="imageType" />&nbsp;Funny
                    </span>
                    <span>
                        <input class="myinput" type="radio" value="2" name="imageType" />&nbsp;Hot Girl</span>
                }
                else
                { 
                    <span>
                        <input class="myinput" type="radio" value="1" name="imageType" />&nbsp;Funny 
                    </span>
                    <span>
                        <input class="myinput" checked="checked" type="radio" value="2" name="imageType" />&nbsp;Hot
                        Girl</span>
                }


            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Source)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Source)
            @Html.ValidationMessageFor(model => model.Source)
        </div>


        <div>

            <input type="file" name="PictureFile" id="PictureFile" />
        </div>

        <div class="loading-upload">
            <img src="/images/funny_loading.gif" />
        </div>
        <div>
            <input class="upload1 btn btn-primary" type="submit" value="Upload" /></div>


    </fieldset>
}

<div>
    @Html.ActionLink("Đến danh sách các bài đăng của bạn", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('.upload1').click(function () {
            $('.loading-upload').show();
            $(this).hide();
        });
    </script>
}

projectk/Views/ImageUpload/Delete.cshtml
@model projectk.Models.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Bạn có chắc là bạn muốn xóa ảnh này?</h3>
<fieldset>
    <legend>Article</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DatePost)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DatePost)
    </div>

    <div class="display-field">
        @{
          
            //if (Model.ThumbnailData != null)
            //{

            <a href="/funny/details/@Model.ID">
                <img alt="@Model.Name" src="@Model.ThumbnailURL" />

            </a> 
                
                
            //}
        }

    </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" />
        |
        @Html.ActionLink("Back to List", "check")
    </p>
}

projectk/Views/ImageUpload/Index.cshtml
@model IEnumerable<projectk.Models.Article>

@{
    ViewBag.Title = "Ảnh của bạn";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    table tr th
    {
        text-align: left;
        

        font: bold 11px "Trebuchet MS", Verdana, Arial, Helvetica,
	sans-serif;
	color: #6D929B;
	border: 1px solid #C1DAD7; 
	letter-spacing: 2px;
	text-transform: uppercase;
	text-align: left;
	padding: 6px 6px 6px 12px;
	 
    }

    table tr td
    {
       

        border: 1px solid #C1DAD7;
	 
	background: #fff;
	padding: 6px 6px 6px 12px;
	color: #6D929B;
    }
</style>
<p>
    @Html.ActionLink("Thêm ảnh", "Create") 
    ,
     @Html.ActionLink("Thêm Video", "Index","VideoUpload")
</p>
<p>
    Danh sách ảnh mà bạn đã đăng
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThumbnailData)
        </th>
           <th>
            @Html.DisplayNameFor(model => model.DatePost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PageView)
        </th> 
        
         <th>
            @Html.DisplayNameFor(model => model.Cat)
        </th>
         <th>
            @Html.DisplayNameFor(model => model.Like)
        </th>
         <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
               @Html.DisplayFor(modelItem => item.Name) 
            </td>
            <td> 
          @*  @if(item.ThumbnailData!=null)
            {
                *@<a href="/funny/details/@item.ID">
                    <img alt="@item.Name" src="@item.ThumbnailURL" />
                </a> 
                
            @*}*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PageView)
            </td>
            <td>
        
            @if (item.Cat == (int)projectk.Models.Cats.Funny)
            { 
                <span>Funny</span>
            }
            else if (item.Cat == (int)projectk.Models.Cats.HotGirl)
            {
                <span>Hotgirl</span>
            }else
            {
             <span>Video</span>
            }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Like)
            </td>
            <td>
               @item.GetStatus()
            </td>

        </tr>
    }

</table>